### ISSUE TITLE
Crashed after attempting to modify values for "Bad Mobs" - 1.19.2

### ISSUE THREAD

**Issue by maloryware** [endorh/simple-config#5]
**Describe the bug**
While inside Minecraft, in the Mods menu, after selecting the "Bad Mobs" mod and opening its configuration menu, I made a few changes to its contents. Upon pressing save, the game crashed.

**To Reproduce**
1. Go to 'Mods'
2. Go to 'Bad Mobs'
3. Go to 'config'
4. Change any value
5. Press 'save'
6. See error

**Expected behavior**
Configuration saves, returns to mod menu.

**Crash Report**
[crash-2023-12-01_16.23.08-client.txt](https://github.com/endorh/simple-config/files/13529918/crash-2023-12-01_16.23.08-client.txt)
[latest.log](https://github.com/endorh/simple-config/files/13529922/latest.log)

**Mod List**
[modlist.txt](https://github.com/endorh/simple-config/files/13529963/modlist.txt)

**Additional context**
Putting together first modpack, likely to be an error on my side, but thought I'd upload anyway.
If this is an error on my side, let me know. I'm still not very clear on what everything in the logs mean but I try my best.

**Comment by endorh** [comment]
Hi, thanks for reporting this crash. Whether your modpack has an issue or not, it's my mod the one that crashed, so a report like this can help me find a potential bug.

At first glance, I can't see anything in your logs that you could have done wrong. I've seen a few mods using 1.19.3 versions, which is likely not an issue if they haven't crashed earlier, but still slightly odd, as most mods are incompatible between 1.19.2 and 1.19.3.

In the logs I can also see two other problems with my mod, when trying to wrap configs for *Sophisticated Backpacks* and *Item Borders*, besides the crash you describe.

Unfortunately, I'm quite short on time rn so I won't be able to look into it for a few weeks. If you find anything else, such as a workaround or a minimal set of mods that lead to the crash (for example, does it still happen with only *Bad Mobs* (and *Simple Config*) installed?), don't hesitate to comment as it'd help me narrow the search when I can get to it.

Nonetheless, thanks again for taking the time to file an issue. ^^

**Comment by maloryware** [comment]
I knew there was at least one other occasion where attempting to configure a different mod crashed, didn't know which one but it's good to see you could catch it!
I'll try doing a minimal set of mods. Glad to be of assistance!

**Comment by maloryware** [comment]
Misclicked, gah

**Comment by maloryware** [comment]
I'll try a minimal set of mods to help narrow it down. I'm glad to be of assistance, and take your time!

**Comment by endorh** [comment]
Hi, I've just released a new version, `1.0.6`, which I think should avoid this crash, though I'm not entirely sure, as I had trouble reproducing it.
It should already be available on Curse Forge.

Sorry it took me so long. I've been too busy irl these past months.

If you have the time to test it, I'd appreciate if you could see if the crash keeps happening. ^^

**Comment by maloryware** [comment]
It's alright, thank you for your time! Personal business takes priority
after all
I'll test the mod as soon as possible and get back to you.

**Comment by maloryware** [comment]
Testing on the originally utilized modpack, no crashes when opening Bad Mobs, Sophisticated Backpacks or Item Borders
Seems to be fixed! Good job :)
Keep up the good work!
